name: Python CI/CD Pipeline

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest  # Utilisation de la dernière version d'Ubuntu pour l'exécution

    steps:
      - uses: actions/checkout@v4  # Récupère le code source depuis le repository GitHub

      - name: Setup Python 3.10
        uses: actions/setup-python@v4  # Configure Python 3.10
        with:
          python-version: '3.10'

      - name: Check Python version
        run: python --version  # Vérifie la version de Python pour s'assurer qu'il est correctement installé

      - name: Install dependencies
        run: |
          pip install --upgrade pip  # Met à jour pip pour éviter les erreurs
          pip install -r requirements.txt  # Installe les dépendances listées dans requirements.txt
          
      - name: Run tests with pytest
        run: |
          pytest -v  # Exécute les tests avec pytest en mode verbeux
