name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo " requirements.txt non trouvé. Installation des dépendances par défaut..."
          pip install pytest paramiko
        fi

    - name: Execute app.py
      run: |
        echo "=== Début de l'exécution de app.py ==="
        if [ -f "app.py" ]; then
          python app.py
          EXIT_CODE=$?
          if [ $EXIT_CODE -ne 0 ]; then
            echo " app.py a terminé avec le code d'erreur $EXIT_CODE"
          else
            echo " app.py exécuté avec succès"
          fi
        else
          echo " Fichier app.py non trouvé"
          exit 1
        fi
        echo "=== Fin de l'exécution ==="

    - name: Run tests
      if: success()  # Ne s'exécute que si app.py a réussi
      run: |
        if [ -d "tests" ]; then
          pytest tests/ -v
        else
          echo "ℹ Aucun dossier tests trouvé - étape ignorée"
        fi
