name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "⚠️ Fichier requirements.txt non trouvé"
        fi
        pip install pytest paramiko
        
    - name: Verify environment
      run: |
        python --version
        pip list
  docker-build-push:
      needs: test
      runs-on: ubuntu-latest
    
      steps:
      - uses: actions/checkout@v4
        
      
      - name: Run tests
        run: |
          python -m unittest discover tests/

      - name: Build Docker image 
        run: |
          docker build -t your-dockerhub-meriem927/sysmonitor:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/system-monitor:latest
      - name: Push Docker image
        run: |
          docker push your-dockerhub-meriem927/sysmonitor:latest   
